---
# this docker-compose is for developing the quotes application
services:

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    volumes:
      - ./frontend:/app
    environment:
      backend_host: backend:5000

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile-dev
    ports:
      - 8888:5000
    volumes:
      - ./backend:/app
