---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
