apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/eficode-academy/flask-quotes-frontend:release
          name: quotes-flask-frontend
          ports:
            - containerPort: 5000
          resources: {}
          imagePullPolicy: Always
          ### using hardcoded env vars
          # env:
          # - name: BACKEND_SVC_HOST
          # value: backend
          # - name: BACKEND_SVC_PORT
          # value: "5000"
          ### using configmap reference
          env:
            # hardcode the namespace
            - name: namespace
              value: default # e.g. student<num> or `default` for kind/minikube
            # load namespace from downward api
            # https://github.com/kubernetes/kubernetes/blob/release-1.0/docs/user-guide/downward-api.md
            # - name: namespace
            # valueFrom:
            # fieldRef:
            # fieldPath: metadata.namespace
            - name: BACKEND_SVC_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_SVC_HOST
            - name: BACKEND_SVC_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: BACKEND_SVC_PORT

status: {}
